name: update-or-create-branch
on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME:
        description: The name of the branch that will be targeted by the pipeline.
        default: ""
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.COMMIT_TOKEN }}
      BRANCH_NAME: ${{ github.event.inputs.BRANCH_NAME }}
      BUILD_TYPE: beta
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm i
      - run: npm run main